---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync-gitlab-cron-job
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.syncCronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: sync-gitlab-runner
            image: {{ .Values.syncCronjob.image }}
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 50m
                memory: 50Mi
              limits:
                cpu: 500m
                memory: 250Mi
            env:
              - name: REMOTE_API_URL
                value: {{ .Values.syncCronjob.remoteApiUrl }}
              - name: ORIGIN_URL
                value: {{ .Values.syncCronjob.originUrl }}
              - name: ORIGIN_URL_USER
                valueFrom:
                  secretKeyRef:
                    name: gitlab-sync-secret
                    key: origin_repo_username
              - name: ORIGIN_URL_SECRET
                valueFrom:
                  secretKeyRef:
                    name: gitlab-sync-secret
                    key: origin_repo_password
              - name: REMOTE_URL
                value: {{ .Values.syncCronjob.remoteUrl }}
              - name: REMOTE_URL_USER
                valueFrom:
                  secretKeyRef:
                    name: gitlab-sync-secret
                    key: destination_repo_username
              - name: REMOTE_URL_SECRET
                valueFrom:
                  secretKeyRef:
                    name: gitlab-sync-secret
                    key: destination_repo_password

