# Default values for gitlab-chart.
# This is a YAML-formatted file.

global:
  edition: ee
  hosts:
    domain: gitlab-lab.dev
    https: true
  enterpriseImages:
    # Default repositories used to pull Gitlab Enterprise Edition images.
    # See the image.repository and workhorse.repository template helpers.
    migrations:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee
    sidekiq:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-sidekiq-ee
    toolbox:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee
    webservice:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ee
    workhorse:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ee
    geo-logcursor:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-geo-logcursor
  communityImages:
    # Default repositories used to pull Gitlab Community Edition images.
    # See the image.repository and workhorse.repository template helpers.
    migrations:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ce
    sidekiq:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-sidekiq-ce
    toolbox:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ce
    webservice:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ce
    workhorse:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ce
  # This exists to support template handling
  psql:
    knownDecompositions:
      - main
      - ci

gitlab-runner:
  enabled: false

gitlab:
  webservice:
    deployments:
      # default answers all external traffic
      default:
        # You must always have at least one with `path: /`
        ingress:
          path: /
        resources:
          requests:
            cpu: 500m
            memory: 2G
        workerProcesses: 2
      # internal-api answers only internal traffic from other charts
      internal-api:
        # this Deployment has no Ingress
        ingress:
          path:
        hpa:
          minReplicas: 1
          maxReplixas: 3
        workerProcesses: 1
        resources:
          requests:
            cpu: 300m
            memory: 1.25G
