global:
  hosts:
    domain: public-digital.lab.myddns.me
    https: false
  ingress:
    configureCertmanager: false
    class: nginx
    tls:
      enabled: false

  psql:
    password:
      useSecret: true
      secret: gitlab-postgresql-secret
      key: postgresql-postgres-password
      file:
    host: gitlab-postgresql.gitlab
    port: 5432
    username: postgres
    database: gitlabhq_production
    applicationName:
    preparedStatements: false

  redis:
    password:
      enabled: true
      secret: gitlab-redis-secret
      key: redis-password
    host: gitlab-redis-master.gitlab
    port: 6379

  minio:
    enabled: true
    credentials: {}
      # secret:

  appConfig:
    omniauth:
      enabled: true
      autoSignInWithProvider:
      syncProfileFromProvider: []
      syncProfileAttributes: ['email']
      allowSingleSignOn: true
      blockAutoCreatedUsers: false
      autoLinkLdapUser: true
      autoLinkSamlUser: true
      autoLinkUser: []
      externalProviders: []
      allowBypassTwoFactor: []
      providers:
      - name: 'openid_connect'
        secret: gitlab-openid-oauth2
        key: provider
## End of global

upgradeCheck:
  enabled: false

certmanager:
  install: false

nginx-ingress:
  enabled: false

redis:
  install: true
  existingSecret: gitlab-redis
  existingSecretKey: redis-password
  usePasswordFile: true
  cluster:
    enabled: true
  metrics:
    enabled: true

## Installation & configuration of stable/prostgresql
## See requirements.yaml for current version
postgresql:
  postgresqlUsername: gitlab
  postgresqlPostgresPassword: ch4ng3m3
  postgresqlPassword: ch4ng3m3
  install: true
  postgresqlDatabase: gitlabhq_production
  image:
    tag: 12.7.0
  usePasswordFile: true
  # existingSecret: 'bogus'
  initdbScriptsConfigMap: 'bogus'
  master:
    extraVolumeMounts:
      - name: custom-init-scripts
        mountPath: /docker-entrypoint-preinitdb.d/init_revision.sh
        subPath: init_revision.sh
    podAnnotations:
      postgresql.gitlab/init-revision: "1"
  metrics:
    enabled: true

registry:
  enabled: false

gitlab-runner:
  install: false

prometheus:
  server:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana-gitlab.lab.myddns.me

gitlab:
  toolbox:
    replicas: 1
    antiAffinityLabels:
      matchLabels:
        app: 'gitaly'
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 50m
        memory: 350M

  gitaly:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 500Mi

  webservice:
    minReplicas: 2
    maxReplicas: 2
    resources:
      limits:
        cpu: 1500m
        memory: 2G
      requests:
        cpu: 300m
        memory: 1.5G
    workhorse:
      resources:
        limits:
          cpu: 500m
          memory: 500M
        requests:
          cpu: 100m
          memory: 100M

  sidekiq:
    minReplicas: 2
    maxReplicas: 2
    resources:
      limits:
        cpu: 1500m
        memory: 2G
      requests:
        cpu: 900m
        memory: 1G

  gitlab-shell:
    minReplicas: 2
    maxReplicas: 2
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 6M

  gitlab-exporter:
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 75m
        memory: 100M
