global:
  syncCronjob:
    schedule: "'*/5 * * * *'"
    image: 'jpgomezivf/python3.8_gitlab_sync:0.1'
    remoteApiUrl: 'icc-un-collective-test.rhone.un-icc.cloud/api/v4/'
    originUrl: 'bitbucket.org'
    remoteUrl: 'icc-un-collective-test.rhone.un-icc.cloud'
  hosts:
    domain: public-digital.lab.myddns.me
    ssh: public-digital.lab.myddns.me
    https: false
    gitlab:
      hostnameOverride: public-digital.lab.myddns.me
      name: public-digital.lab.myddns.me
  ingress:
    configureCertmanager: false
    class: nginx
    tls:
      enabled: false

  psql:
    password:
      useSecret: true
      secret: gitlab-postgresql-secret
      key: postgresql-postgres-password
      file:
#    host: postgres-postgresql-ha-pgpool.postgres
    host: gitlab-postgresql.gitlab
    port: 5432
    username: postgres
    database: gitlabhq_production
    applicationName:
    preparedStatements: false

  redis:
    password:
      enabled: false
    host: redis-master.redis
    port: 6379

  minio:
    enabled: true
    credentials: {}

#  grafana:
#    enabled: false

  appConfig:
    lfs:
      bucket: gitlab-lfs-storage
      connection: {}
    artifacts:
      bucket: gitlab-artifacts-storage
      connection: {}
    uploads:
      bucket: gitlab-uploads-storage
      connection: {}
    packages:
      bucket: gitlab-packages-storage
      connection: {}
    backups:
      bucket: gitlab-backup-storage
      tmpBucket: gitlab-tmp-storage


    omniauth:
      enabled: true
      autoSignInWithProvider:
      syncProfileFromProvider: []
      syncProfileAttributes: ['email']
      allowSingleSignOn: true
      blockAutoCreatedUsers: false
      autoLinkLdapUser: true
      autoLinkSamlUser: true
      autoLinkUser: []
      externalProviders: []
      allowBypassTwoFactor: []
      providers:
        - name: 'openid_connect'
          secret: gitlab-openid-oauth2
          key: provider
## End of global

upgradeCheck:
  enabled: false

certmanager:
  install: false

nginx-ingress:
  enabled: false

redis:
  install: false
postgresql:
#  install: false
  install: true
  postgresqlUsername: gitlab
  postgresqlPostgresPassword: ch4ng3m3
  postgresqlPassword: ch4ng3m3
  postgresqlDatabase: gitlabhq_production
  image:
    tag: 12.7.0
  usePasswordFile: true
  existingSecret: gitlab-postgresql-secret
#  initdbScriptsConfigMap: 'bogus'
  master:
    extraVolumeMounts:
      - name: custom-init-scripts
        mountPath: /docker-entrypoint-preinitdb.d/init_revision.sh
        subPath: init_revision.sh
    podAnnotations:
      postgresql.gitlab/init-revision: "1"
  metrics:
    enabled: true

registry:
  enabled: false

gitlab-runner:
  install: false

prometheus:
  install: false

shared-secrets:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi

gitlab:
  toolbox:
    replicas: 1
    registry:
      enabled: false
    antiAffinityLabels:
      matchLabels:
        app: 'gitaly'
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 50m
        memory: 350M
    init:
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 6M

  gitaly:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 500Mi
    init:
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100M
    persistence:
      enabled: true
      storageClass: "qnap-nfs"
      size: 50Gi

  webservice:
    global:
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: | 
            sub_filter '</head>' ' <style>#login-pane {display: none !important;}#signin-container p.gl-mt-3{display: none;}.login-page .brand-holder{text-align: center;}a[href="https://about.gitlab.com"]{display: none;}</style> </head>';
    minReplicas: 2
    maxReplicas: 2
    registry:
      enabled: false
    resources:
      limits:
        cpu: 1500m
        memory: 2G
      requests:
        cpu: 300m
        memory: 1.5G
    workhorse:
      resources:
        limits:
          cpu: 500m
          memory: 500M
        requests:
          cpu: 100m
          memory: 100M
    init:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 50M

  sidekiq:
    minReplicas: 2
    maxReplicas: 2
    registry:
      enabled: false
    resources:
      limits:
        cpu: 1500m
        memory: 2G
      requests:
        cpu: 900m
        memory: 1G
    init:
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 50m
          memory: 100M

  gitlab-shell:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    minReplicas: 2
    maxReplicas: 2
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 6M
    init:
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 6M

  gitlab-exporter:
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 75m
        memory: 100M
    init:
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 6M
  migrations:
    resources:
      limits:
        cpu: 150m
        memory: 1Gi
      requests:
        cpu: 75m
        memory: 100M
    init:
      resources:
        limits:
          cpu: 100m
          memory: 150Mi
        requests:
          cpu: 50m
          memory: 6M
