global:
  hosts:
    gitlab:
      hostnameOverride: public-digital.lab.myddns.me
    domain: public-digital.lab.myddns.me
    https: false
  ingress:
    configureCertmanager: false
    class: nginx
    tls:
      enabled: false

  psql:
    password:
      useSecret: true
      secret: gitlab-postgresql-secret
      key: postgresql-postgres-password
      file:
    host: postgres-postgresql-ha-pgpool.postgres
    port: 5432
    username: postgres
    database: gitlabhq_production
    applicationName:
    preparedStatements: false

  redis:
    password:
      enabled: false
    host: redis-master.redis
    port: 6379

  minio:
    enabled: true
    credentials: {}

#  grafana:
#    enabled: false

  appConfig:
    lfs:
      bucket: gitlab-lfs-storage
    artifacts:
      bucket: gitlab-artifacts-storage
    uploads:
      bucket: gitlab-uploads-storage
    packages:
      bucket: gitlab-packages-storage
    backups:
      bucket: gitlab-backup-storage
      tmpBucket: gitlab-tmp-storage


    omniauth:
      enabled: true
      autoSignInWithProvider:
      syncProfileFromProvider: []
      syncProfileAttributes: ['email']
      allowSingleSignOn: true
      blockAutoCreatedUsers: false
      autoLinkLdapUser: true
      autoLinkSamlUser: true
      autoLinkUser: []
      externalProviders: []
      allowBypassTwoFactor: []
      providers:
        - name: 'openid_connect'
          secret: gitlab-openid-oauth2
          key: provider
## End of global

upgradeCheck:
  enabled: false

certmanager:
  install: false

nginx-ingress:
  enabled: false

redis:
  install: false
postgresql:
  install: false

registry:
  enabled: false

gitlab-runner:
  install: false

prometheus:
  install: false

shared-secrets:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi

gitlab:
  toolbox:
    replicas: 1
    antiAffinityLabels:
      matchLabels:
        app: 'gitaly'
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 50m
        memory: 350M
    init:
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 6M

  gitaly:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 500Mi
    init:
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 6M
    persistence:
      enabled: true
      storageClass: "qnap-nfs"
      size: 50Gi

  webservice:
    minReplicas: 2
    maxReplicas: 2
    resources:
      limits:
        cpu: 1500m
        memory: 2G
      requests:
        cpu: 300m
        memory: 1.5G
    workhorse:
      resources:
        limits:
          cpu: 500m
          memory: 500M
        requests:
          cpu: 100m
          memory: 100M
    init:
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 6M

  sidekiq:
    minReplicas: 2
    maxReplicas: 2
    resources:
      limits:
        cpu: 1500m
        memory: 2G
      requests:
        cpu: 900m
        memory: 1G
    init:
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 6M

  gitlab-shell:
    minReplicas: 2
    maxReplicas: 2
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 6M
    init:
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 6M

  gitlab-exporter:
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 75m
        memory: 100M
    init:
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 6M
  migrations:
    resources:
      limits:
        cpu: 150m
        memory: 150Mi
      requests:
        cpu: 75m
        memory: 100M
    init:
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 6M
